### DISCUSSION TITLE
How to configure both Fluss and Paimon for S3 storage.

### DISCUSSION THREAD

**Discussion by maarek** [apache/fluss#471] [Q&A] [answered]
I am just running the docker-compose quickstart and I was wondering if one could provide an example configuration to configure Fluss + Paimon for S3 storage. The docs are a little sparse on s3 and setting the config but there is no information on paimon configuration for s3.

**Comment by wuchong** [comment]
cc @luoyuxia , could you give some hints here?

**Comment by luoyuxia** [comment, marked as answer]
@maarek Hi, thanks for your attention and sorry for missing document about it. I think you can follow these steps:
1. Configure s3 for Fluss
Follow the document [fluss s3](https://alibaba.github.io/fluss-docs/docs/maintenance/filesystems/s3/) to configure s3 for Fluss.
If you want to read the Fluss with Flink, please remember to copy fluss-fs-os into `FLINK_HOME/lib`

2. Configure s3 for write into Paimon
You'll only need to configure s3 filesystem in Flink since it'll use Flink's filesystem to write to paimon.. You can follow the document [filesystem-s3](https://nightlies.apache.org/flink/flink-docs-stable/docs/deployment/filesystems/s3/) to configure s3 in Flink 

Hope it can help.

**Comment by maarek** [comment]
@luoyuxia Thank you for your reply. 

I am following the instructions here : [https://alibaba.github.io/fluss-docs/docs/quickstart/flink/](https://alibaba.github.io/fluss-docs/docs/quickstart/flink/)

I have added the following configuration to the docker containers (I wasn't sure tablet-server config vs coordinator config) to connect to s3 compatible local minio server. 

First, I do not see it storing anything in s3 with these configs. This is with the `fluss/fluss:0.5.0` docker container. I do see in the logs that it sees that the s3 access key is set, but it does not seem to do anything with it nor error out on connection. I see it still storing data locally within the data.dir. Is there some sort of internal syncing occurring between local tmp storage and s3? Am I configured incorrectly?

As well, when you say flink needs to be configured for s3 and paimon, what then is the configuration below doing when setting lakehouse.storage to paimon and setting the config metastore and warehouse to be on the local filesystem? 

logs:
```bash
tablet-server-1  | 2025-02-28 01:11:41,332 INFO  com.alibaba.fluss.fs.s3.S3FileSystemPlugin                   [] - fs.s3a.access.key is set, using provided access key id and secret.
```

coordinator:
```
    environment:
      - |
        FLUSS_PROPERTIES=
        zookeeper.address: zookeeper:2181
        coordinator.host: fluss.coordinator-server
        remote.data.dir: s3://warehouse/fluss
        s3.endpoint: http://minio:9000/
        s3.access-key: admin
        s3.secret-key: password
        s3.region: us-phoenix-1
        table.datalake.enabled: true
        lakehouse.storage: paimon
        paimon.catalog.metastore: filesystem
        paimon.catalog.warehouse: /tmp/paimon
```

tablet-server:
```
    environment:
      - |
        FLUSS_PROPERTIES=
        zookeeper.address: zookeeper:2181
        tablet-server.host: fluss.tablet-server
        data.dir: /tmp/fluss/data
        kv.snapshot.interval: 0s
        remote.data.dir: s3://warehouse/fluss
        s3.endpoint: http://minio:9000/
        s3.access-key: admin
        s3.password: password
        s3.region: us-phoenix-1
        table.datalake.enabled: true
        lakehouse.storage: paimon
        paimon.catalog.metastore: filesystem
        paimon.catalog.warehouse: /tmp/paimon
```
